*PatentParse_V14 successfully parses a folder of weekly XML files dated 2012+ and outputs the utility patents to a single csv file;
%MACRO PatentParse_V14(filePath);
%GLOBAL cleanText;
FILENAME srcFile &filePath;
%LET abText = ;
OPTIONS NoQuoteLenMax;
data work.patent_data;
	INFILE srcFile DSD DLM='0A'X LRECL=5000 TRUNCOVER;
	INPUT lineText  :$5000.;
	FORMAT docSection $50. grant_num $7. grant_date $8. grant_type $2. main_uspc $8.
		cpc_m_section $8. cpc_m_class $8. cpc_m_subclass $8. cpc_m_main_group $8. cpc_m_subgroup $8.
		cpc_m_position $2. cpc_m_value $2.
		inv_title $300. abstract $5000. tempText $5000.
		; 
*Determine which section of the document is currently being processed (retains value from line-to-line, only changes when a new section is encountered);

	IF SUBSTR(lineText,1,5) = "<?xml" THEN docSection = 'New Doc';
	IF SUBSTR(lineText,1,22) = "<publication-reference" THEN docSection = 'Publication Reference';
	IF SUBSTR(lineText,1,22) = "<application-reference" THEN docSection = 'Application Reference';
	IF SUBSTR(lineText,1,21) = "<classifications-ipcr" THEN docSection = 'IPC Class';
	IF SUBSTR(lineText,1,9) = "<main-cpc" THEN docSection = 'CPC Main';
	IF SUBSTR(lineText,1,12) = "<further-cpc" THEN docSection = 'CPC Further';
	IF SUBSTR(lineText,1,24) = "<classification-national" AND ((docSection = "IPC Class") 
		or (docSection = "CPC Main") or (docSection = "CPC Further"))
		THEN docSection = 'USPC Class';
	IF SUBSTR(lineText,1,20) = "<us-references-cited" THEN docSection = 'US Refs';
	IF SUBSTR(lineText,1,27) = "<us-field-of-classification" THEN docSection = 'US Field Class';
	IF SUBSTR(lineText,1,21) = "<us-related-documents" THEN docSection = 'US Docs';
	IF SUBSTR(lineText,1,10) = "<abstract " THEN docSection = 'Abstract';
	IF SUBSTR(lineText,1,11) = "</abstract>" THEN docSection = 'End of Abstract';
*At end of patent OUTPUT sections of patent if utility patent and set all vars to empty regardless of patent type ;
		IF lineText = '</us-patent-grant>' and grant_type = "ut" THEN DO;
			OUTPUT patent_data;
			docSection = .;
			grant_num = .;
			grant_date = .;
			grant_type = .;
			main_uspc = .;
			inv_title = .;
			abstract = .;
			cpc_m_section = .;
			cpc_m_class = .; 
			cpc_m_subclass = .;  
			cpc_m_main_group = .;  
			cpc_m_subgroup = .; 
			cpc_m_position = .;  
			cpc_m_value = .; 
		END;
		IF lineText = '</us-patent-grant>' and grant_type ^= "ut" THEN DO;
			docSection = .;
			grant_num = .;
			grant_date = .;
			grant_type = .;
			main_uspc = .;
			inv_title = .;
			abstract = .;
			cpc_m_section = .;
			cpc_m_class = .; 
			cpc_m_subclass = .;  
			cpc_m_main_group = .;  
			cpc_m_subgroup = .; 
			cpc_m_position = .;  
			cpc_m_value = .; 
		END;
	* Capture the grant number;
	IF docSection = 'Publication Reference' AND SUBSTR(lineText,1,11) = "<doc-number" THEN DO;
		grant_num = substr(lineText,14,7);
	END;
	*Capture the grant date;
		IF docSection = 'Publication Reference' AND SUBSTR(lineText,1,6) = "<date>" THEN DO;
		grant_date = substr(lineText,7,8);
		END;
	*Capture the grant type;
		IF docSection = 'Application Reference' AND SUBSTR(lineText,24,9) = "appl-type" THEN DO;
		grant_type = SUBSTR(lineText,35,2);
		END;
	*Capture CPC main classification fields;
		IF docSection = 'CPC Main' AND SUBSTR(lineText,1,9) = "<section>" THEN DO;
			lineText = TRANWRD(lineText, ",", " ");
			lineText = TRANWRD(lineText, "'", "");
			lineText = TRANWRD(lineText, "(", "");
			lineText = TRANWRD(lineText, ")", "");
			lineText = TRANWRD(lineText, "%", "");
			lineText = TRANWRD(lineText, "&", "");
			CALL EXECUTE('%RemoveTag('||lineText||', '||grant_num||')');
			cpc_m_section = RESOLVE('&cleanText');
		END;
		IF docSection = 'CPC Main' AND SUBSTR(lineText,1,7) = "<class>" THEN DO;
			lineText = TRANWRD(lineText, ",", " ");
			lineText = TRANWRD(lineText, "'", "");
			lineText = TRANWRD(lineText, "(", "");
			lineText = TRANWRD(lineText, ")", "");
			lineText = TRANWRD(lineText, "%", "");
			lineText = TRANWRD(lineText, "&", "");
			CALL EXECUTE('%RemoveTag('||lineText||', '||grant_num||')');
			cpc_m_class = RESOLVE('&cleanText');
		END;
		IF docSection = 'CPC Main' AND SUBSTR(lineText,1,10) = "<subclass>" THEN DO;
			lineText = TRANWRD(lineText, ",", " ");
			lineText = TRANWRD(lineText, "'", "");
			lineText = TRANWRD(lineText, "(", "");
			lineText = TRANWRD(lineText, ")", "");
			lineText = TRANWRD(lineText, "%", "");
			lineText = TRANWRD(lineText, "&", "");
			CALL EXECUTE('%RemoveTag('||lineText||', '||grant_num||')');
			cpc_m_subclass = RESOLVE('&cleanText');
		END;
		IF docSection = 'CPC Main' AND SUBSTR(lineText,1,12) = "<main-group>" THEN DO;
			lineText = TRANWRD(lineText, ",", " ");
			lineText = TRANWRD(lineText, "'", "");
			lineText = TRANWRD(lineText, "(", "");
			lineText = TRANWRD(lineText, ")", "");
			lineText = TRANWRD(lineText, "%", "");
			lineText = TRANWRD(lineText, "&", "");
			CALL EXECUTE('%RemoveTag('||lineText||', '||grant_num||')');
			cpc_m_main_group = RESOLVE('&cleanText');
		END;
		IF docSection = 'CPC Main' AND SUBSTR(lineText,1,10) = "<subgroup>" THEN DO;
			lineText = TRANWRD(lineText, ",", " ");
			lineText = TRANWRD(lineText, "'", "");
			lineText = TRANWRD(lineText, "(", "");
			lineText = TRANWRD(lineText, ")", "");
			lineText = TRANWRD(lineText, "%", "");
			lineText = TRANWRD(lineText, "&", "");
			CALL EXECUTE('%RemoveTag('||lineText||', '||grant_num||')');
			cpc_m_subgroup = RESOLVE('&cleanText');
		END;
		IF docSection = 'CPC Main' AND SUBSTR(lineText,1,17) = "<symbol-position>" THEN DO;
			cpc_m_position = substr(lineText,18,1);
		END;
		IF docSection = 'CPC Main' AND SUBSTR(lineText,1,22) = "<classification-value>" THEN DO;
			cpc_m_value = substr(lineText,23,1);
		END;
	*Capture the Main USPC classification;
		IF docSection = 'USPC Class' AND SUBSTR(lineText,1,21) = "<main-classification>" THEN DO;
			main_USPC = scan(substr(lineText,(find(lineText,"<main-classification>")+21),8),1,"<");
			main_USPC = TRANWRD(main_USPC, " ", "-");
		END;
	*Capture the invention title;
		IF SUBSTR(lineText,1,16) = "<invention-title" THEN DO;
			lineText = TRANWRD(lineText, ",", " ");
			lineText = TRANWRD(lineText, "'", "");
			lineText = TRANWRD(lineText, "(", "");
			lineText = TRANWRD(lineText, ")", "");
			lineText = TRANWRD(lineText, "%", "");
			lineText = TRANWRD(lineText, "&", "");
			CALL EXECUTE('%RemoveTag('||lineText||', '||grant_num||')');
			inv_title = RESOLVE('&cleanText');
		END;
	*Capture the abstract;
		IF docSection = 'End of Abstract' THEN DO;
			abstract = COMPBL(SYMGET('abText'));
			CALL SYMPUT("abText","");
		END;
		IF docSection = 'Abstract' THEN DO;
			IF lineText ^= '' THEN DO;
				lineText = TRANWRD(lineText, ",", " ");
				lineText = TRANWRD(lineText, "'", "");
				lineText = TRANWRD(lineText, "(", "");
				lineText = TRANWRD(lineText, ")", "");
				lineText = TRANWRD(lineText, "&#x2032", "");
				lineText = TRANWRD(lineText, "&#x2033", "");
				CALL EXECUTE('%RemoveTag('||lineText||', '||grant_num||')');
				tempText = RESOLVE('&cleanText');
				*The following code is capturing most abstracts that break over multiple lines
				but some chemical related abstracts are only getting the first couple of abstract
				lines captured and missing the last one or two lineTexts that contain abstract text;
				IF SYMGET('abText') ^= '' THEN CALL SYMPUT("abText", SYMGET('abText') || tempText);
					ELSE CALL SYMPUT("abText",tempText);
		 	END;
		END;
*Retain values of variables for a patent until the end of the patent is reached;
	Retain docSection grant_num grant_date grant_type main_uspc inv_title abstract 
		cpc_m_section cpc_m_class cpc_m_subclass cpc_m_main_group cpc_m_subgroup
		cpc_m_position cpc_m_value ; 
	Run;
OPTIONS QuoteLenMax;
data work.patent_data;
	set work.patent_data (drop=lineText docSection tempText);
	run;

%MEND PatentParse_V14;

